language: clojure
lein: 2.8.1
jdk: openjdk8
script:
    - lein --version
    - lein bikeshed
    - lein cljfmt check
    - lein eastwood
    - lein kibit
    - lein midje
    - lein cljsbuild once dev
    - lein cljsbuild once prod
    - lein cljsbuild test
notifications:
  email:
    - tech+travis@ona.io
  slack: onaio:snkNXgprD498qQv4DgRREKJF
